### ISSUE TITLE
New-SFTPSession : Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by TheLamed** [darkoperator/Posh-SSH#378]
Hello! I wrote script in powershell for deploying project. I use Posh-SSH for uploading project and run some commands on the server. This script worrks on local computer, but when I use Github Action - its throws an error

Github action code
```
name: WebDeploy

on:
  push:
    branches:
    - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install required PowerShell modules
      shell: powershell
      run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module Posh-SSH -ErrorAction Stop
    - name: Show that the Action works
      shell: powershell
      run: |
          Get-Module -Name Posh-SSH -ListAvailable | Select Path
          Import-Module Posh-SSH
    - name: Run deploy
      run: .\web-deploy-script.ps1
      shell: powershell
```

I`m installing Posh-SSH, and running my script.
I get this error https://i.stack.imgur.com/qkE52.png
```
New-SFTPSession : Object reference not set to an instance of an object.
At D:\a\projectfolder\web-deploy-script.ps1:24 char:16
+ ... tpSession = New-SFTPSession -ComputerName $HostIP -Credential $Creden ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Renci.SshNet.SftpClient:SftpClient) [New-SFTPSession], NullReferenceException
    + FullyQualifiedErrorId : SSH.NewSftpSession
```

My script code
```
$secpasswd = ConvertTo-SecureString $Password -AsPlainText -Force
$Credentials = New-Object System.Management.Automation.PSCredential($User, $secpasswd)
$sftpSession = New-SFTPSession -ComputerName $HostIP -Credential $Credentials #error in this line
```
